# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  hello-world:
    jobs:
      - setup

jobs:
  setup:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            choco install git -y
            choco install premake5 -y  # Ensure Premake is installed
            choco install gh -y  # GitHub CLI for releases
