# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-default
    shell: powershell.exe

jobs:
  setup:
    machine: windows-default
    steps:
      - checkout
      - run:
          name: Test Setup Job
          command: |
            choco install git -y
            choco install premake5 -y
            choco install gh -y

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - setup
