# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  windows-executor:
    machine:
      image: "windows-server-2022" # Use latest Windows image
    shell: powershell.exe # Use PowerShell for commands

jobs:
  setup:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            choco install git -y
            choco install premake5 -y  # Ensure Premake is installed
            choco install gh -y  # GitHub CLI for releases

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - setup
