# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-default
    shell: powershell.exe

jobs:
  setup:
    machine: windows-default
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: |
          choco install git -y
          choco install premake5 -y  # Ensure Premake is installed
          choco install gh -y  # GitHub CLI for releases
  build:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Generate Build Files
          command: |
            cd config\Windows
            generate_projects.bat
      - run:
          name: Compile Project
          command: |
            msbuild AurionCore.sln /p:Configuration=Dist /m
      - persist_to_workspace:
          root: .
          paths:
            - bin/

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - setup
      - build:
          requires:
            - setup
