# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  setup-build-test:
    jobs:
      - setup
      - build:
        requires:
          - setup

jobs:
  setup:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            choco install git -y
            choco install premake5 --pre -y
            choco install gh -y
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Build VS Project Files
          command: |
            dir
