# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    machine:
      image: windows-default
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - build
